//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentcrudapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string dob { get; set; }
        public string sub1 { get; set; }
        public Nullable<int> num1 { get; set; }
        public string sub2 { get; set; }
        public Nullable<int> num2 { get; set; }
        public string sub3 { get; set; }
        public Nullable<int> num3 { get; set; }
        public string sub4 { get; set; }
        public Nullable<int> num4 { get; set; }
    }
}
